### ISSUE TITLE
Distributed Tutorial

### ISSUE THREAD

**Issue by JordiManyer** [gridap/GridapWorkshopNCI2023#4]
So on the topic of the tutorials on Gadi: 

I think we all agree that the 3D navier-stokes example would be nice, but it could put quite a lot of stress on the project SUs if everyone launched a job with a ton of resources. 
So I was thinking we could do a sort of live strong scalability test, where we launch one job per table (so around 8 jobs in total) with different amount of processors, then ask for the results and see how good they are (I would of course test this beforehand to see if it actually makes sense). Then while the jobs are running we show a pre-computed result in paraview. This also takes some stress out of the server since only we as instructors will be rendering things in it. 
If Alberto says something about scalability in the morning, it could be a nice way to round things off.

**Comment by amartinhuertas** [comment]
I think it is a fantastic idea!
